### ISSUE TITLE
Conjuntos: metodos e implementaciones.

### ISSUE THREAD

**Issue by bizk** [bizk/progra_2#10]
Fede, me faltan los **metodos e implementaciones de los conjuntos**, para poder laburar con el tema de diccionarios, cuando puedas subilo! gracias!

**Comment by Fedejp** [comment]
Ya los subí arreglados Santi. Fijate que en tus metodos de diccionario no los nombrás bien.
Los que hice yo se llaman "ConjuntoUA" y "ConjuntoTMA" (recomiendo usar el TMA para todos los métodos)
